/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package proyecto.progra1;

import java.util.ArrayList;

/**
 *
 * @author pricesmart
 */
public class Gam3 extends javax.swing.JFrame {

    /**
     * Creates new form Gam3
     */
    public Gam3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Lectura2 = new javax.swing.JTextField();
        Continuar = new javax.swing.JButton();
        Lectura1 = new javax.swing.JTextField();
        Lectura3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Arial Black", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Fantasio Adventure");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 280, 50));

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Caballero");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 200, -1, -1));

        Lectura2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lectura2.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Lectura2.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Lectura2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura2ActionPerformed(evt);
            }
        });
        jPanel1.add(Lectura2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 120, 620, 40));

        Continuar.setBackground(new java.awt.Color(153, 0, 0));
        Continuar.setFont(new java.awt.Font("Dialog", 1, 11)); // NOI18N
        Continuar.setText("Continuar");
        Continuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinuarActionPerformed(evt);
            }
        });
        jPanel1.add(Continuar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 340, -1, -1));

        Lectura1.setForeground(new java.awt.Color(102, 102, 102));
        Lectura1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lectura1.setText("Ej. Rudeus Greyrat");
        Lectura1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Lectura1.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Lectura1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura1ActionPerformed(evt);
            }
        });
        jPanel1.add(Lectura1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 140, 20));

        Lectura3.setForeground(new java.awt.Color(102, 102, 102));
        Lectura3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        Lectura3.setText("Ej. Mago");
        Lectura3.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        Lectura3.setDisabledTextColor(new java.awt.Color(255, 255, 255));
        Lectura3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Lectura3ActionPerformed(evt);
            }
        });
        jPanel1.add(Lectura3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 140, 20));

        jLabel8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("¡Bienvenido a la Aventura!");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Ingrese el nombre: ");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        jLabel5.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Ingrese su clase:  ");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Dialog", 0, 10)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Mago");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 200, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyecto/progra1/panorama.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 640, 410));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Lectura2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura2ActionPerformed

    private int clicks = 0;

    AventuraStarts2 start = new AventuraStarts2();
    ArrayList<Hero> héroe = new ArrayList();
    
private String[] textos = {
    "La tierra de Avidus es una tierra llena de fantasía...",
    "Donde los seres humanos conviven con hombres bestia, elfos, enanos y muchas otras especies.", 
    "Un día sin embargo, un incidente llevó a que el mundo se dividiera...",
    "El gran Rey Dragón luchó contra el primer Rey Humano. ",
    "La destrucción fue tal que dividió al continente de San Avidus en dos partes.", 
    "De este modo las especies que una vez convivieron empezaron a odiarse.", 
    "Por suerte el continente fue dividido por la mitad lo que apagó las ganas de sangre de ambas partes.",
        "Pasaron 500 años desde ese incidente...",
        "Un día un malvado ser llamado 'Desarrollador'...",
        "Decidió que sería divertido aviviar nuevamente esta antigua disputa.",
        "El continente separado volvió a unirse...",
        "Y tras esto las disputas entre humanos y todas las demás especies empezaron.",
        "Comenzó la gran guerra entre Humanos y 'demonios'",
        "Nombre que fue utilizado por los humanos para referirse a todas las especies que no eran humanas.",
        "La guerra fue una de aniquilación donde ambos bandos buscaban el control total del mundo.",
        "El mundo de Avidus necesitaba un milagro...",
        "Esta tierra que tantos años había experimentado odio necesitaba ser salvada...",
        "¡Se bienvenido al mundo de Fantasio Adventure!",
        "Crea tu personaje",
        "Conque tu nombre es:",
        "Bien, ahora todo los pasos necesarios han sido hechos...",
        "Tu aventura ahora comenzará, ¿lograrás salvar a la humanidad?",
        "O tal vez... ¿la condenarás?",
        "No puedo esperar a verlo...",
        "***************************************************",
        "Oscuridad... todo estaba muy oscuro...",
        "Voz en algún lugar: ´¡Oyeeee!´",
        "*Escuchaba una voz...*",
        "Voz desconocida:\n'¡Despertá!'",
        "*Abrí lentamente los ojos y me encontré a... ¿un hada?*",
        "Hada1",
        "Batalla",
        "",
        "",
};
    
    private void ContinuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinuarActionPerformed
       if (clicks < textos.length) {
        Lectura2.setText(textos[clicks]);
        if (textos[clicks].equals("Conque tu nombre es:")) {
            int vida = 0;
            int mana = 0;
            int daño = 0;
            int defensa = 0;
            
             String nombre = Lectura1.getText();
             String clase = Lectura3.getText().toLowerCase();

        if (clase.equals("mago")) {
            vida = 550;
            mana = 300;
            daño = 150;
            defensa = 80;
        } else if (clase.equals("caballero")) {
            vida = 600;
            mana = 200;
            daño = 190;
            defensa = 100;
        } else {
            vida = 600;
            mana = 200;
            daño = 190;
            defensa = 100;
        }
        Hero héroe = new Hero(nombre, clase, vida, mana, daño, defensa);
            this.héroe.add(héroe);
            
            
            String texto = "Conque tu nombre es: " + héroe.getNombre() + "";
            Lectura2.setText(texto);
        
            nombre = " ";
            clase = " ";
            Lectura1.setText(nombre);
            Lectura3.setText(clase);
//            start.setVisible(true);
//            start.setLocale(null);
           }
        
           if (textos[clicks].equals("Hada1")) {
               Hada1 hada = new Hada1();
               
               hada.setVisible(true);
               hada.setLocale(null);
           }
           if (textos[clicks].equals("Batalla")) {
               batallaMenu battle = new batallaMenu();
               
               battle.setVisible(true);
               battle.setLocale(null);
           }
        clicks++;
           
       }
    }//GEN-LAST:event_ContinuarActionPerformed

    private void Lectura1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura1ActionPerformed

    private void Lectura3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Lectura3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Lectura3ActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Continuar;
    private javax.swing.JTextField Lectura1;
    private javax.swing.JTextField Lectura2;
    private javax.swing.JTextField Lectura3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
